{% set name = "pyserial" %}
{% set version = "3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c77e014170dfffbd816e6ffc205e9842efb10be9f58ec16d3e8675b4925cddb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - serial

about:
  home: https://github.com/pyserial/pyserial
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python serial port access library
  description: |
    pySerial encapsulates the access for the serial port. It provides backends
    for Python running on Windows, OSX, Linux, BSD (possibly any POSIX
    compliant system) and IronPython. The module named "serial" automatically
    selects the appropriate backend.
  doc_url: https://pyserial.readthedocs.io/en/latest/
  doc_source_url: https://github.com/pyserial/pyserial/blob/master/documentation/index.rst
  dev_url: https://github.com/pyserial/pyserial

extra:
  recipe-maintainers:
    - shaunwbell
    - carlodri
